#!/usr/bin/python3

import io
import os
import urllib.request
import zipfile

# URL of the Trade Data
URL = "https://data.binance.vision/data/spot/daily/trades/BTCUSDT/BTCUSDT-trades-2023-02-26.zip"

PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "_data")

print(f"Saving data to {PATH}")

# Download the file using urllib
with urllib.request.urlopen(URL) as response:
    data = response.read()

# Unzip the contents of the file to the parent directory
with zipfile.ZipFile(io.BytesIO(data)) as zip_file:
    zip_file.extractall(PATH)
